#!/bin/bash
# omarchy-thunderbird install script
# Run once after cloning the plugin, or re-run to update.

set -euo pipefail

PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TB_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/thunderbird"

echo "omarchy-thunderbird: installing from $PLUGIN_DIR"

# ── 1. Install Thunderbird ────────────────────────────────────────────────────
omarchy pkg add thunderbird
echo "  Thunderbird installed."

# ── 2. Find (or create) the default profile ───────────────────────────────────
PROFILE="$("$PLUGIN_DIR/bin/omarchy-tb-profile" 2>/dev/null)" || PROFILE=""

if [[ -z "$PROFILE" ]]; then
  echo "  No Thunderbird profile found — creating one..."
  # Run TB briefly to create a default profile
  timeout 8 thunderbird --headless 2>/dev/null || true
  PROFILE="$("$PLUGIN_DIR/bin/omarchy-tb-profile" 2>/dev/null)" || PROFILE=""
fi

if [[ -z "$PROFILE" ]]; then
  echo "  WARNING: could not locate or create a TB profile."
  echo "  Run thunderbird once to create a profile, then re-run install.sh."
else
  echo "  Using profile: $PROFILE"
fi

# ── 3. Apply user.js preferences ─────────────────────────────────────────────
if [[ -n "$PROFILE" ]]; then
  # Merge: append our prefs that aren't already set
  USERJS="$PROFILE/user.js"
  if [[ -f "$USERJS" ]]; then
    # Remove any of our keys that may already exist, then append ours
    while IFS= read -r line; do
      key=$(echo "$line" | grep -oP '(?<=user_pref\(")[^"]+' || true)
      [[ -n "$key" ]] && sed -i "/user_pref(\"${key//\./\\.}\"/d" "$USERJS" 2>/dev/null || true
    done < "$PLUGIN_DIR/profile/user.js"
    cat "$PLUGIN_DIR/profile/user.js" >> "$USERJS"
  else
    cp "$PLUGIN_DIR/profile/user.js" "$USERJS"
  fi
  echo "  Applied user.js preferences."
fi

# ── 4. Set up userChrome.css theming ──────────────────────────────────────────
if [[ -n "$PROFILE" ]]; then
  CHROME_DIR="$PROFILE/chrome"
  mkdir -p "$CHROME_DIR"

  # Render the applied stylesheet for the current theme: the active theme is inlined
  # into the :root block, so theming works with no userChromeJS loader.
  CURRENT_THEME=$(omarchy theme current 2>/dev/null | tr '[:upper:]' '[:lower:]' | tr ' ' '-' || true)
  [[ -z "$CURRENT_THEME" ]] && CURRENT_THEME="catppuccin"
  echo "$CURRENT_THEME" > "$CHROME_DIR/omarchy-active-theme"
  "$PLUGIN_DIR/bin/omarchy-tb-render-css" "$CURRENT_THEME" --output "$CHROME_DIR/userChrome.css"
  "$PLUGIN_DIR/bin/omarchy-tb-render-css" "$CURRENT_THEME" --kind content --output "$CHROME_DIR/userContent.css"
  echo "  Rendered userChrome.css + userContent.css for theme: $CURRENT_THEME"

  # Write the initial set-theme.uc.js (for users who run a userChromeJS loader).
  cat > "$CHROME_DIR/set-theme.uc.js" << UCJS
// Auto-generated by omarchy-thunderbird
(function() {
  const theme = "${CURRENT_THEME}";
  document.documentElement.setAttribute("data-omarchy-theme", theme);
})();
UCJS
fi

# ── 4b. Install the unread-count backend on PATH (for the bar widget) ─────────
BIN_SRC="$PLUGIN_DIR/bin/omarchy-thunderbird-unread"
BIN_DEST="/usr/local/bin/omarchy-thunderbird-unread"
if [[ -L "$BIN_DEST" ]] && [[ "$(readlink -f "$BIN_DEST")" == "$(readlink -f "$BIN_SRC")" ]]; then
  echo "  unread backend already on PATH."
elif (( EUID == 0 )); then
  ln -sf "$BIN_SRC" "$BIN_DEST" && echo "  Installed unread backend to $BIN_DEST."
elif command -v sudo >/dev/null 2>&1; then
  sudo ln -sf "$BIN_SRC" "$BIN_DEST" && echo "  Installed unread backend to $BIN_DEST."
fi

# ── 5. Install policies.json for system-wide managed preferences ──────────────
_install_policies() {
  mkdir -p /usr/lib/thunderbird/distribution
  cp "$PLUGIN_DIR/bin/policies.json" /usr/lib/thunderbird/distribution/policies.json
  echo "  Installed policies.json."
}
if (( EUID == 0 )); then
  _install_policies
elif command -v sudo >/dev/null 2>&1; then
  sudo bash -c "mkdir -p /usr/lib/thunderbird/distribution && cp '$PLUGIN_DIR/bin/policies.json' /usr/lib/thunderbird/distribution/policies.json"
  echo "  Installed policies.json."
else
  pkexec bash -c "mkdir -p /usr/lib/thunderbird/distribution && cp '$PLUGIN_DIR/bin/policies.json' /usr/lib/thunderbird/distribution/policies.json"
  echo "  Installed policies.json."
fi

# ── 6. Install theme-set hook ─────────────────────────────────────────────────
chmod +x "$PLUGIN_DIR/hooks/theme-set"
omarchy hook install theme-set "$PLUGIN_DIR/hooks/theme-set"
echo "  Installed theme-set hook."

# ── 7. Wire OS keybindings into Hyprland ──────────────────────────────────────
HYPR_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"
HYPR_MAIN="$HYPR_CONFIG_DIR/hyprland.lua"
BINDINGS_FILE="$HYPR_CONFIG_DIR/bindings.lua"

if [[ ! -f "$HYPR_MAIN" ]]; then
  echo "  WARNING: $HYPR_MAIN not found — skipping keybinding wiring."
  echo "  Add to your hyprland.lua manually: require(\"thunderbird.bindings\")"
else
  # Copy bindings.lua to ~/.config/thunderbird-bindings.lua so it's on Lua path
  cp "$PLUGIN_DIR/bin/bindings.lua" "$HYPR_CONFIG_DIR/thunderbird-bindings.lua"
  if ! grep -q "thunderbird-bindings" "$HYPR_MAIN"; then
    printf '\n-- omarchy-thunderbird keybindings\nrequire("hypr.thunderbird-bindings")\n' >> "$HYPR_MAIN"
    echo "  Wired keybindings into $HYPR_MAIN"
  else
    # Re-copy to update
    echo "  Keybindings already wired (updated)."
  fi
fi

# ── 7b. Add Thunderbird to Hyprland autostart ─────────────────────────────────
AUTOSTART="$HYPR_CONFIG_DIR/autostart.lua"
if [[ -f "$AUTOSTART" ]] && ! grep -q "thunderbird" "$AUTOSTART"; then
  printf '\n-- omarchy-thunderbird: start Thunderbird at login (opens on workspace 4)\no.launch_on_start("thunderbird")\n' >> "$AUTOSTART"
  echo "  Added Thunderbird to autostart."
elif grep -q "thunderbird" "${AUTOSTART:-/dev/null}" 2>/dev/null; then
  echo "  Thunderbird already in autostart."
else
  echo "  No autostart.lua found — add manually: o.launch_on_start(\"thunderbird\")"
fi

# ── 8. Set as default mail client ─────────────────────────────────────────────
TB_DESKTOP="org.mozilla.Thunderbird.desktop"
MAIL_MIMES=(
  x-scheme-handler/mailto
  message/rfc822
  text/calendar
  text/vcard
  text/x-vcard
  x-scheme-handler/webcal
  x-scheme-handler/webcals
)

# User-level
xdg-settings set default-url-scheme-handler mailto "$TB_DESKTOP" 2>/dev/null || true
for mime in "${MAIL_MIMES[@]}"; do
  xdg-mime default "$TB_DESKTOP" "$mime"
done
echo "  Registered MIME types for user."

# System-wide
chmod +x "$PLUGIN_DIR/bin/set-system-default"
echo "  Setting system-wide default mail client (requires sudo)..."
if (( EUID == 0 )); then
  bash "$PLUGIN_DIR/bin/set-system-default"
elif command -v sudo >/dev/null 2>&1; then
  sudo bash "$PLUGIN_DIR/bin/set-system-default"
else
  pkexec bash "$PLUGIN_DIR/bin/set-system-default"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "Done! Start Thunderbird with: thunderbird"
echo ""
echo "Theme switches automatically with: omarchy theme set <name>"
echo "All 22 Omarchy stock themes are supported."
